# Generated by Django 5.2.5 on 2025-08-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directors',
            old_name='nome',
            new_name='name',
        ),
    ]
